application: poolwhip
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: .*/logo.png
  static_files: logo.png
  upload: logo.png

- url: .*/pic2.jpg
  static_files: pic2.jpg
  upload: pic2.jpg

- url: /stylesheets
  static_dir: stylesheets
  
- url: /scripts
  static_dir: scripts
  
- url: /.*
  script: main.app


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest